# Generated by Django 2.1.4 on 2018-12-27 06:58

from django.db import migrations, models
from api.models import User
from datetime import date


def insert_data(apps, schema_editor):
    User = apps.get_model("api", "User")

    User(user_name="user1",
         birth_day=date(1995, 1, 30),
         gender=True,
         password="MTIzNDU2Nzg=",
         ).save()
    User(user_name="user2",
         birth_day=date(1995, 11, 23),
         gender=False,
         password="MTIzNDU2Nzg=",
         ).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('gender', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(insert_data)
    ]
