dist: xenial
language: python
python:
  - '3.7.1'
services:
  - postgresql
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - psql -c 'create database default;' -U postgres
  - psql -c "CREATE USER hello WITH PASSWORD 'django';" -U postgres
script:
  - timeout 100s make test
