dist: xenial
language: python
env:
  - WORKDIR=/home/travis/build/tsrnd/hello-django
matrix:
  fast_finish: true
python:
  - '3.7.1'
install:
  - pip install -r requirements.txt
script:
  - find . -iname "*.py" | xargs pylint --load-plugins pylint_django
  # - timeout 100s pipenv run pytest