dist: xenial
language: python
python:
  - '3.7.1'
services:
  - docker
cache:
  directories:
    - $HOME/.docker/images/
before_install:
  - make load-images
install:
  - cp .env.example .env
script:
  - timeout 120s make test
before_cache:
  - make save-images
