dist: xenial
language: python
python:
  - '3.7.1'
services:
  - docker
cache:
  directories:
    - $HOME/.docker/images/
before_install:
  - make load-images
install:
  - cp .env.example .env
  - pip install -U lintly
  - docker-compose build app
script:
  - docker-compose run app pylint myproject myapp --output-format=json | lintly --format=pylint-json --api-key=$GITHUB_ACCESS_TOKEN
  - docker-compose run app pytest
before_cache:
  - make save-images
