dist: xenial
language: python
python:
  - '3.7.1'
services:
  - docker
cache:
  directories:
    - $HOME/.docker/images/
    - $HOME/.cache/pip/
before_install:
  - make ci-load-images
install:
  - cp .env.example .env
script:
  - make ci-lint
  - make ci-test
before_cache:
  - make ci-save-images
