dist: xenial
language: python
matrix:
  fast_finish: true
python:
  - '3.7.1'
install:
  - pip install -r requirements.txt
script:
  - pylint --load-plugins pylint_django -E team2
  - timeout 100s pipenv run pytest