dist: xenial
language: python
python:
  - '3.7.1'
services:
  - docker
cache:
  directories:
    - $HOME/docker
    - $HOME/.cache/pip/
before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - cp .env.example .env
install:
  - pip install pipenv
  - pip install coverage
  - pipenv install --dev
script:
  - make up-data
  - sleep 3
  - make migrate
  # - timeout 100s make test
  - timeout 100s coverage run --source='.' manage.py test myapp.products
before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
