dist: xenial
language: python
python:
  - '3.7.1'
services:
  - docker
env:
  - WORKDIR=/home/travis/build/tsrnd/hello-django
matrix:
  fail_fast: true
cache:
  directories:
    - $HOME/.docker/images/
before_install:
  - make load-images
install:
  - cp .env.example .env
script:
  - docker-compose build app
  - 'docker-compose run app pylint --msg-template="pylint-response: {path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" myproject myapp'
  - docker-compose run app pytest
after_failure:
  - docker-compose run app ./traviscomment.sh
before_cache:
  - make save-images
