dist: xenial
language: python
python:
  - '3.7.1'
services:
  - docker
env:
  - WORKDIR=/home/travis/build/tsrnd/hello-django
matrix:
  fail_fast: true
cache:
  directories:
    - $HOME/docker
    - $HOME/.cache/pip/
before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - cp .env.example .env
  - chmod +x $WORKDIR/traviscomment.sh
install:
  - pip install pipenv
  - pip install coverage
  - pip install pylint
  - pip install pylint-django
  - pipenv install --dev
script:
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_PULL_REQUEST
  - find . -iname "*.py" | xargs pylint --load-plugins pylint_django
  - make up-data
  - sleep 3
  - make migrate
  - timeout 100s coverage run --source='.' manage.py test myapp.products
  - coverage report
after_failure:
  - $WORKDIR/traviscomment.sh
before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
