version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/code
    expose:
      - 8000
    ports:
      - 8000:8000
    links:
      - data:data
    environment:
      DATABASE_URL: 'postgres://hello:django@data:5432/default'
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  data:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'default'
      POSTGRES_USER: 'hello'
      POSTGRES_PASSWORD: 'django'
    restart: always
