# Generated by Django 2.1.4 on 2019-01-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False},
        ),
    ]
