# Generated by Django 2.1.4 on 2019-01-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='Board',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='Topic',
        ),
    ]
