# Generated by Django 2.1.4 on 2019-01-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190106_1230'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
